frappe/frappe_docker

docker-compose.yml
This is the same fix on develop branch. Sorry for that
=> Fixed mariadb ports mapping

Dockerfile, dbench
- clone bench master
- install yarn globally
- set lang as C.UTF-8
=> Make work on latest

Dockerfile, dbench, docker-compose.yml
Signed-off-by: Chinmay Pai <chinmaydpai@gmail.com>
=> redis: fix redis

Dockerfile
This PR removes 30 layers, and also updates to the latest node version
=> Condensing Dockerfile, and a few other things

build/bench/Dockerfile
install nvm in user home
allows npm install -g
install yarn in v10
=> fix: bench image

build/common/commands/new.py
=> fix: worker new-site command

.gitignore, README.md, development/README.md
This PR:
-  fixes the .gitignore
- Improves Development documentation to be idiot-proof
- adds development section to main readme
- makes styling of main readme more consistent
- fixes grammar and sentence issues
=> Improve documentation development

.vscode/extensions.json, development/README.md
- Add extensions.json so that recommended extensions are automatically proposed to the user on vscode
- small fix in readme, some links were being sanitized by github
=> Improve documentation for development

build/frappe-nginx/Dockerfile, build/frappe-nginx/v11.Dockerfile, build/frappe-nginx/v12.Dockerfile, build/frappe-socketio/Dockerfile, build/frappe-socketio/v11.Dockerfile, build/frappe-socketio/v12.Dockerfile
Simply prints a few node versions for ease of debug and record keeping
=> Enumerate node packages

build/bench/Dockerfile
add bash-completion package
remove install_packages duplicates
workdir set to /home/frappe
=> feat(bench): bash-completion

build/bench/Dockerfile
fix debugger fail after bench update
error locale.Error: unsupported locale setting
add locale to image
=> fix(bench): debugger fail after bench update

build/common/commands/check_connection.py, build/common/commands/doctor.py
=> fix: python container healthcheck

build/common/nginx-default.conf.template
add updates from frappe/bench to config
=> fix: nginx config

.travis.yml
first attempt to get builds on master running
=> fix: travis wrapper script for build on master

.travis.yml, build/common/nginx-default.conf.template
=> fix: fix wrapper script to build on master branch

build/erpnext-nginx/install_app.sh, build/frappe-nginx/Dockerfile, build/frappe-nginx/v11.Dockerfile, build/frappe-nginx/v12.Dockerfile
=> fix(frappe-nginx): fix missing /rsync

README.md, development/README.md
mention to add site for production deployment
mention to start bench for development deployment
fixes #181
=> fix: improve readme

build/frappe-nginx/docker-entrypoint.sh
Fix appropriate host and port for socketio in nginx container message
=> fix(frappe-nginx): fix connection message

README.md, build/common/commands/push_backup.py, build/common/commands/restore_backup.py
REGION required to for s3 compatible backup/restore
=> fix: required region s3 compatible backup/restore

build/common/commands/auto_migrate.py, build/common/commands/background.py, build/common/commands/backup.py, build/common/commands/check_connection.py, build/common/commands/console.py, build/common/commands/doctor.py, build/common/commands/migrate.py, build/common/commands/new.py, build/common/commands/push_backup.py, build/common/commands/restore_backup.py, build/common/commands/worker.py
* add missing `__main__` call to commands.py
* remove unnecessary imports
* fix backup WITH_FILES logic
* follow python semantics (?)
=> fix: make semantic changes to commands

build/common/commands/migrate.py, build/common/commands/new.py
- fix: mysql error during set db password
- fix: always disable maintenance mode after migration
=> fix: commands

.travis.yml, tests/docker-test.sh
As per https://github.com/frappe/frappe_docker/issues/221
- Every day v12 will be migrated to develop in this build/test
- Ensures stability of devops functionality using docker
- Ensures backups, push backup to cloud and restore backup from cloud works
- Ensures all site operation commands work
=> test: all worker commands

.travis.yml, build/erpnext-nginx/v13-beta.Dockerfile, build/erpnext-worker/v13-beta.Dockerfile, build/frappe-nginx/v13-beta.Dockerfile, build/frappe-socketio/v13-beta.Dockerfile, build/frappe-worker/v13-beta.Dockerfile, travis.py
https://discuss.erpnext.com/t/frappe-erpnext-version-13-0-0-beta-1-released/61088
=> build v13-beta images

development/README.md
Both bench init and get-app need to be on the same version branch. 
Mismatch results into errors while installing app
=> Update branch version while installing app

build/bench/Dockerfile, build/frappe-worker/Dockerfile, build/frappe-worker/v11.Dockerfile, build/frappe-worker/v12.Dockerfile, build/frappe-worker/v13-beta.Dockerfile
use wkhtmltopdf for buster amd64
=> update: use wkhtmltopdf for buster_amd64

build/common/commands/restore_backup.py
only download latest backup for sites when restoring from cloud
=> fix: only download and restore latest backup

development/.vscode/launch.json, development/README.md
=> feat: debug workers in vscode devcontainers

README.md, development/.vscode/launch.json, development/README.md
=> build: erpnext v12.9.3

development/README.md
As I was going through the installation process, I noticed the steps for VSCode Remote Containers were a little unclear.
I also a fixed a typo in Line 14
=> Updated VSCode Remote Containers extension

.devcontainer/Dockerfile, .devcontainer/docker-compose.yml, build/bench/Dockerfile, development/README.md
- Instead of building one more image locally, updated the bench image.
- update to readme as per changes
=> feat(frappe/bench): allow 5 benches

build/common/worker/docker-entrypoint.sh
wait for connections before creating new site
=> feat: wait for connection before creating site

build/common/commands/push_backup.py
=> refactor: backup site_config.json

tests/pwd.yml
=> test: play with docker

.travis.yml, build/common/commands/restore_backup.py, tests/docker-test.sh
if encryption key exists for a site, it will now be restored to the site config while restoring site
=> fix: restore encryption key on site restore

.devcontainer/docker-compose.yml, build/bench/Dockerfile, build/common/commands/backup.py, build/common/commands/check_connection.py, build/common/commands/console.py, build/common/commands/migrate.py, build/common/commands/new.py, build/common/commands/restore_backup.py, build/common/common_site_config.json.template, build/common/worker/docker-entrypoint.sh, build/erpnext-nginx/Dockerfile, build/erpnext-nginx/install_app.sh, development/README.md, docs/site-operations.md, installation/frappe-postgresql/docker-compose.yml, installation/frappe-postgresql/env-local, installation/frappe-postgresql/env-production, tests/docker-test.sh
=> feat: add postgres support to frappe-worker

build/common/commands/check_connection.py, build/common/commands/doctor.py, build/common/worker/docker-entrypoint.sh, docs/site-operations.md
doctor --ping-service postgres:5432 -p mariadb:3306
=> feat: ping additional services using doctor

tests/pwd.yml
=> fix: pwd socketio hostname

build/common/commands/new.py, build/common/commands/restore_backup.py, build/common/commands/utils.py
* add a wrapper method run_command
* remove os.system calls
* use f-strings for commands
=> fix: use subprocess instead of os to run commands

.gitignore, build/common/commands/auto_migrate.py, build/common/commands/check_connection.py, build/common/commands/constants.py, build/common/commands/migrate.py, build/common/commands/new.py, build/common/commands/push_backup.py, build/common/commands/restore_backup.py, build/common/commands/utils.py, build/erpnext-nginx/install_app.sh
move common functions to utils
move constants to constants.py
=> refactor: add utils and constants

development/.vscode/settings.json
=> fix: workaround for vscode debugger issue

.devcontainer/docker-compose.yml, development/README.md
=> refactor: Disable PostgreSQL by default, fixes #317

build/common/commands/restore_backup.py
Fixes https://github.com/frappe/frappe_docker/issues/325
=> fix: grant privileges for rds when restoring backup

docs/custom-apps-for-production.md
=> docs: Clarify requirement of repository naming and branch naming

build/common/worker/docker-entrypoint.sh, tests/docker-test.sh
execute frappe commands with bench
=> feat: frappe commands

build/common/worker/bench, build/common/worker/docker-entrypoint.sh, build/frappe-worker/Dockerfile, docs/site-operations.md, tests/docker-test.sh, tests/pwd.yml
bench sub commands did not work.
fix to allow args to be passed to bench command
=> fix: accept args for bench commands

docs/site-operations.md
Add docs for delete/drop site in site-operations.md
=> [skip travis] Update site-operations.md

docs/site-operations.md
the command "up -d" goes at the end of the line.
=> minor docker-compose syntax fix

build/common/worker/healthcheck.sh
allow redis databases in healthcheck
=> fix: health check

development/.vscode/launch.json
As recommended in `README.md` when Bench Web is debugged separately.
Make it easier to launch honcho with required services (except web).
=> build: Add honcho start to launch.json

build/common/commands/new.py
changes reverted, broke new site creation
for mariadb-galera or any other db, use custom py files and execute them on entrypoint.
=> revert changes for mariadb-galera

build/common/commands/new.py, development/.vscode/launch.json, development/README.md
=> fix: make new command compatible with MySQL 8

development/README.md
Added a warning to prevent a common mistake that I made during my installation. 
Sourced from https://discuss.erpnext.com/t/how-to-get-started-with-the-official-docker-image/60710/2
=> Update README.MD for clarity

build/bench/Dockerfile, build/frappe-nginx/Dockerfile, build/frappe-worker/Dockerfile
- fixes password expiry error for old images
- update NodeJS to latest minor and patch lts release
=> Non root password expiry

.travis.yml, build/bench/Dockerfile, build/erpnext-nginx/Dockerfile, build/erpnext-nginx/install_app.sh, build/erpnext-worker/Dockerfile, build/frappe-nginx/Dockerfile, build/frappe-socketio/Dockerfile, build/frappe-worker/Dockerfile, travis.py
Reverts frappe/frappe_docker#402
=> Revert "feat: make images arm64 compatible"

build/frappe-nginx/Dockerfile
Fix for failed build: https://travis-ci.com/github/frappe/frappe_docker/jobs/479671433#L1327
=> fix(frappe-nginx): make directory before copying assets

build/frappe-nginx/Dockerfile, build/frappe-worker/Dockerfile
https://discuss.erpnext.com/t/release-notes-erpnext-v13-beta-11-and-frappe-v13-beta-10/70900
=> Release: ERPNext v13-Beta.11 and Frappe v13-Beta.10

build/erpnext-nginx/install_app.sh
=> fix(erpnext-nginx): install erpnext or custom app dependencies

CONTRIBUTING.md, README.md
Add section about wiki in contribution section
Mention about wiki in README
Mention about cron job in README
=> docs: improve docs

build/common/commands/gevent_patch.py, build/common/worker/docker-entrypoint.sh, build/frappe-worker/Dockerfile, docs/environment-variables.md
=> feat(frappe-worker): option to set gevent as gunicorn worker-class

.travis.yml, docs/docker-swarm.md, docs/multi-bench.md, docs/single-bench.md, docs/site-operations.md, tests/docker-test.sh, travis.py
=> chore: change ci script to build v13

build/bench/Dockerfile, build/erpnext-nginx/Dockerfile, build/erpnext-worker/Dockerfile, build/frappe-nginx/Dockerfile, build/frappe-nginx/docker-entrypoint.sh, build/frappe-socketio/Dockerfile, build/frappe-socketio/package.json, build/frappe-worker/Dockerfile, development/.vscode/launch.json, docker-compose.yml, env-local, env-production, travis.py
use nodejs v14
allow build args to pass repo and branch
add WORKER_CLASS under erpnext-python in docker-compose.yml
=> feat: improve build

build/erpnext-nginx/Dockerfile, build/erpnext-nginx/install_app.sh
closes https://github.com/revant/erpnext_feature_board/issues/15
=> feat: allow custom frappe branch during asset image build

build/common/worker/healthcheck.sh
Add bash flags and removed 
- `errexit` - better for fast fail of healthchecks
- `allexport` - export vars by default
- `nolog` - not to add in history (optional)
=> refactor: remove exports, add bash flags healthchecks

.travis.yml, CONTRIBUTING.md, build/common/worker/docker-entrypoint.sh, build/common/worker/healthcheck.sh, build/common/worker/install_app.sh, build/erpnext-nginx/install_app.sh, build/frappe-nginx/docker-entrypoint.sh, build/frappe-socketio/docker-entrypoint.sh, frappe-installer, tests/check-format.sh, tests/docker-test.sh
- https://google.github.io/styleguide/
- also made some changes like removed `&&` where it is not necessary
- avoid using `let` and `expr` 
- use underline and new line variable instead of `\e[1m\e[4m` and `\n`
=> refactor: style as per google style guide (tried)

build/frappe-nginx/Dockerfile, build/frappe-worker/Dockerfile
Some of the Dockerfiles missed the part to clean up apt lists, this PR make sure every Dockerfile to do it!
=> Make sure apt lists cleaned up in Dockerfile

build/erpnext-nginx/Dockerfile, build/frappe-nginx/Dockerfile, build/frappe-socketio/Dockerfile, build/frappe-worker/Dockerfile
- Update Python from 3.7 to 3.9
- Use bullseye images instead of buster
=> build: Update base images

.github/workflows/build_stable.yml
Fails: https://github.com/frappe/frappe_docker/runs/4107326014?check_suite_focus=true  😬
=> ci: Fix stable build

.github/workflows/build_stable.yml
using https://github.com/fregante/setup-git-user
=> ci: change git creds action for helm release

build/frappe-nginx/Dockerfile
=> feat(frappe-nginx): use nginxinc/nginx-unprivileged image

development/.vscode/settings.json, development/README.md, development/vscode-example/launch.json, development/vscode-example/settings.json
=> feat: allow devcontainer vscode configuration

.github/workflows/lint.yml
Now Lint workflow will run only if shell scripts are changed.
=> ci(lint): Specify paths that trigger workflow

.editorconfig, .github/workflows/lint.yml, .github/workflows/pre-commit-autoupdate.yml, .pre-commit-config.yaml, .prettierignore, CONTRIBUTING.md
- Added .editorconfig
- Added pre-commit config
- Updated lint workflow to use pre-commit
- Added pre-commit autoupdate workflow to update hooks once a week
- Added guide to CONTRIBUTING.md
Closes #602
=> chore: Use pre-commit framework

build/bench/Dockerfile
=> fix: Bench initialization with ERPNext v12 on frappe/bench

docs/single-bench.md
=> Change erpnext-python volumes description

.github/workflows/build_bench.yml, .github/workflows/build_develop.yml, build/bench/Dockerfile, docker-bake.hcl
=> Change bench target names and move CI to separate workflow

.github/workflows/build_bench.yml, .github/workflows/build_develop.yml, .github/workflows/build_stable.yml
=> Make build workflows run if files that they're are described in change

compose.yaml, overrides/compose.proxy.yaml
=> Move Traefik config to appropriate override

images/worker/Dockerfile
=>  fix: Letterheads missing

docs/setup-options.md
`erpnext.yaml` > `compose.erpnext.yaml`
=> docs: Fix file name

.github/workflows/build_stable.yml, images/worker/configure.py, images/worker/patched_bench_helper.py, images/worker/push_backup.py, tests/_check_connections.py, tests/test_frappe_docker.py
=> Build for v12

images/worker/Dockerfile
=> fix: gunicorn config for containers

development/README.md
=> docs: use additional service during development

development/README.md
=> fix: config commands

.github/scripts/get_latest_tags.py, .github/workflows/build_stable.yml
=> ci: build v14 images

docs/compose/compose.multi-bench-ssl.yaml, docs/compose/compose.multi-bench.yaml
Redirect HTTP to HTTPS
HTTP should be redirected to HTTPS if SSL is required
=> Update multi-bench yaml

docker-bake.hcl, images/nginx/Dockerfile, images/socketio/Dockerfile, images/worker/Dockerfile
=> feat: allow custom git repos

.github/workflows/build_develop.yml, .github/workflows/build_stable.yml, .github/workflows/docker-build-push.yml
=> ci: fix inputs.platforms

tests/conftest.py, tests/utils.py
=> Fix builds failing

.github/workflows/build_stable.yml, .github/workflows/docker-build-push.yml, .github/workflows/lint.yml, development/README.md, docker-bake.hcl, images/bench/Dockerfile
=> add python 3.10

development/README.md
=> docs: mention to install honcho in env

.github/scripts/get_latest_tags.py, images/nginx/Dockerfile, images/worker/Dockerfile, tests/conftest.py
https://github.com/frappe/frappe_docker/issues/866
=> fix: install frappe/payments for v14 and develop

compose.yaml
Delete the unnecessary volume definition and add read-only to assets on the backend
=> edits on volumes definition 

images/bench/Dockerfile
As https://discuss.erpnext.com/t/upgrade-to-version-13-or-newer-to-continue-receiving-regular-fixes/93052
version-12 is no more supported, we can remove it from docker bench image
closes : #896
=> feat: remove version-12 dependencies

images/bench/Dockerfile
=> fix(bench): add dependencies to build python using pyenv

development/README.md
=> Added the --resolve-deps flag to dev install

development/README.md, images/bench/Dockerfile
=> fix: install node and python envs for v13

docker-bake.hcl, images/nginx/Dockerfile, images/worker/Dockerfile
=> fix: install correct nodejs as per frappe version

images/bench/Dockerfile, images/worker/Dockerfile
This will make the image a little bit tidier 🎉
=> Prevent leaving pip install cache in Docker image

development/installer.sh
Ref: https://stackoverflow.com/a/21210966
=> fix: incorrect eval for boolean in installer.sh

images/worker/Dockerfile, images/worker/install-app.sh
- add git command to worker image, keep the git data in install-app script
- add config directory
=> fix: create config directory in worker image

overrides/compose.erpnext.yaml
Required for background jobs that need css assets for sending emails
=> fix: mount assets on workers

compose.yaml, example.env, images/nginx/Dockerfile, images/nginx/nginx-template.conf, pwd.yml
=> feat: make client_max_body_size configurable via env

.github/scripts/update_example_env.py, example.env
=> fix: remove frappe version from .env

.github/scripts/update_example_env.py
=> fix: pass single string as arg

images/production/Containerfile
fix github rate limit error on bench install-app
=> fix: remove git remotes for erpnext

.github/workflows/build_develop.yml, .github/workflows/build_stable.yml, images/bench/Dockerfile, images/custom/Containerfile, images/production/Containerfile
=> fix: add weasyprint dependencies

images/custom/Containerfile
for OS that mess up permission
fixes #1050
=> fix: set exec for nginx entrypoint

docs/migrate-from-multi-image-setup.md, pwd.yml
payments is optional dep for erpnext
https://github.com/frappe/erpnext/pull/33245
=> fix: remove payments

docs/setup-options.md
=> docs: fix migration steps

docs/development.md, overrides/compose.mariadb-shared.yaml, overrides/compose.traefik-ssl.yaml, tests/conftest.py
remove bind mount
use docker volumes
=> fix: use docker volumes

compose.yaml, docs/custom-apps.md
This may help a bit to clarify what additional changes are expected when using custom images.
This was taken after the post https://github.com/frappe/frappe_docker/issues/876#issuecomment-1261834758
=> Clarification on how to use custom image

development/installer.sh
=> fix frape typo

.github/workflows/docker-build-push.yml
Reverts frappe/frappe_docker#1098
=> Revert "Build arm64 images in addition to amd64 images"

docs/single-server-example.md
The previous command added a new line where the SITES variable was set while keeping the old line where it is set to erp.example.com. So I changed it to update it with sed instead
=> docs: change command for updating sites in single server example

images/bench/Dockerfile
=> fix: use stable bench branch

.github/workflows/build_bench.yml, .github/workflows/build_stable.yml, .github/workflows/docker-build-push.yml, CONTRIBUTING.md, docker-bake.hcl, images/bench/Dockerfile, images/custom/Containerfile, images/production/Containerfile
use debian bookworm
use updated wkhtmltopdf
override python and nodejs versions
=> ci: refactor

docs/custom-apps.md
python image 3.10.12 onwards gets built on bookworm
=> docs: update python and nodejs version

.github/workflows/build_develop.yml
=> ci: fix develop build

images/bench/Dockerfile
used for frappe develop branch
=> fix: add python 3.11 and nodejs 18

docker-bake.hcl, images/nginx/nginx-template.conf
updated python and node versions
=> Compat 2022

docs/troubleshoot.md
remove docs related letsencrypt companion
=> docs: remove obsolete docs

tests/test_frappe_docker.py
https://github.com/frappe/frappe/pull/21786
=> fix: use ping api instead of version api

docs/bench-console-and-vscode-debugger.md, docs/development.md
=> docs: change sitename as per installer.py

docs/setup_for_linux_mac.md
=> Add Clarity 

compose.yaml, docs/development.md, docs/single-compose-setup.md, pwd.yml
=> fix: consume default queue

docs/development.md, docs/migrate-from-multi-image-setup.md, docs/setup_for_linux_mac.md, docs/single-server-example.md, docs/site-operations.md, pwd.yml
fix command usage and docs
fixes issue#1256
=> fix: new-site command

docs/single-server-example.md
=> Updated grammer in single-server-example.md

docs/custom-apps.md
Updating documentation examples to version-15
The examples on this page are no longer valid for any working configuration. These changes will give an example of how to build erpnext with payments app on version-15.
=> Update custom-apps.md for version-15

devcontainer-example/devcontainer.json
Enhance dev container YAML to meet standards and integrate personal GitHub environment token
Refactored the dev container YAML configuration to adhere to best practices and coding standards. This includes optimizing container setup and dependencies for smoother development workflows. Additionally, a personal GitHub environment token was integrated for secure authentication and access to GitHub resources within the container environment. This improvement enhances both security and usability, streamlining the development process.
Currently works on Linux (Arch)
Currently, pulling private repos was a challenge and required generating a new SSH token to the dev container. Wanted to make this …
=> chore! :alien: Enhance dev container YAML

devcontainer-example/devcontainer.json
no ssh service installed in frappe/bench:latest
for custom usage add to gitignored .devcontainer
=> fix(dev): remove ssh from post start command

compose.yaml
Adding the platform parameter to be able to run this compose in non amd64 platforms
=> #1370 Adding platform parameter

docs/custom-apps.md
* The variables in the container files have default values already. Update the documentation to make this clear and add examples of how to customize.
* Bump example versions to the most updated minor version of each dependency (NodeJS, Python).
* Default to using `docker` instead of `buildah`, which works fine for most users.
=> Improve custom apps documentation

.gitignore, images/custom/Containerfile
added build library in custom image needed to build arm64 binaries which are not readily available 
eg: arm64 binaries need for print designer app refer this [link](https://github.com/frappe/print_designer?tab=readme-ov-file#faq)
=> add build library for arm64 binaries

example.env
Existing Reference is pointed to non-existing file, fixed that
=> Updated example.env to include correct reference to doc

overrides/compose.https.yaml, overrides/compose.proxy.yaml, overrides/compose.traefik.yaml
This updates a few yaml files to refer to an updated version of Traefik that is recently supported and fixes some recent vulnerabilities.
Fixes: https://www.cert.europa.eu/publications/security-advisories/2024-102/ and probably some others
=> Update Traefik container from deprecated v2.6 to v2.11

docker-bake.hcl
=> ci: push base and build images tags

docs/environment-variables.md, docs/troubleshoot.md
After a long and painful migration process, I am adding the documentation I wish had been present to make the experience smoother, clarifying the use of certain variable and the steps for troubleshooting database access errors.
=> Add instruction regarding compose variables and add troubleshooting steps for debugging database access

docs/troubleshoot.md
=> chore: fix pre-commit lint for md file

.github/workflows/docker-build-push.yml
Fixes https://github.com/frappe/frappe_docker/issues/1511, add  docker/setup-qemu-action@v3 step
=> Fix arm64 runner build

docs/list-of-containers.md
=> docs: fix broken link

pwd.yml
after research for connection issues in docker between multiple containers it is found that adding a network bridge fixes that
=> fix: add network bridge to pwd.yml fix connection error

README.md
=> fix: add quotes into command

development/installer.py, docs/development.md, docs/migrate-from-multi-image-setup.md, docs/setup_for_linux_mac.md, docs/single-server-example.md, docs/site-operations.md, tests/conftest.py
=> fix: --no-mariadb-socket & --mariadb-root-password is DEPRECATED

README.md, docs/custom-apps-podman.md
This is a full guide on building an image with custom apps using Podman.
=> Building an image with custom apps using podman

docs/custom-apps-podman.md
Added a guide on autostart pod using system daemon
=> Autostart pod on system boot

.pre-commit-config.yaml, development/installer.py
Description to be found in https://github.com/frappe/frappe_docker/commit/3a5b15cf5d4a73bb7245612760bdab51df8f4cf0
=> Fix `installer.py`

README.md
Just a file extension typo fix
=> docs: fix typo yaml -> yml in README.md

.github/workflows/docker-build-push.yml
=> ci: for arm64 build frappe/erpnext like frappe/bench

.github/workflows/docker-build-push.yml, images/bench/Dockerfile, images/custom/Containerfile, images/production/Containerfile
Related to https://github.com/frappe/frappe/pull/31719
=> build: add pkg-config deb package in build layer
