frappe/frappe_docker

- dbench
- Added missing shebang
- Fixed malformed multi line variables
- Removed unnecessary su (which is not working in this way anyway)
- Added missing error handling (unsupported options as well as missing argument)
- Simplified the whole script (without the removal of features, hopefully?)
Note: It might be better to change -c to the default, and add a -f (or similar) to open the inside-docker shell (current default) (so dbench would be the same as bench).
> fixing various issues with dbench

- README.md
it took me a long time to way to login after initially installing. I eventually found out the default by looking into closed issues on github. I just added a line to the readme to make it clear for future users to get up and running faster.
> Updated README.md to clarify initial admin password

- conf/mariadb-conf.d/my.cnf
According with:
- https://discuss.erpnext.com/t/important-mariadb-version-10-3-action-required-before-update/37717
- https://github.com/frappe/bench/issues/681
this PR solved issues #40 and #3
> Removed innodb configs because cause error with MariaDB 10.3

- .travis.yml
`--skip-bench-mkdir` does not exist, and it breaks travis
we replace it with `--ignore-exists`
Signed-off-by: Chinmay Pai <chinmaydpai@gmail.com>
> travis: replace unexisting command option

- dbench
fixed a problem where typing `bench setup nginx` or something of that sort, would not send the command to the container
> "bench setup anything-else" should work now

- Dockerfile
Please include this commit to decrease the size of the docker image, the "rm -rf /var/lib/apt/lists/*" it is not usefull if it is not used in the same stage of the apt-get install RUN, similar with pip cache.
References:
- https://linux.die.net/man/8/apt-get
- https://stackoverflow.com/questions/9510474/removing-pips-cache
- https://semaphoreci.com/blog/2016/12/13/lightweight-docker-images-in-5-steps.html
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file;
(b) I understand and agree that this project and the contribution
are public and that a record of the contribution (including all
personal information I submit with it, including my …
> Clean cache in the same RUN to get a smaller image

- Dockerfile
- docker-compose.yml
This way wkhtmltox is working with patched qt, last version avaible for debian stretch, the 0.12.5-1 doesn't seem to be supported yet
> chore: install wkhtmltox correctly

- build/erpnext-assets/docker-entrypoint.sh
- build/frappe-assets/docker-entrypoint.sh
Nginx will now wait up to 10 seconds for frappe-python and frappe-socketio to be available
> Fixes #101

- README.md
- development/README.md
INSTALL_APPS variable fix, previous failed
site_config has db info instead of common_site_config
> fix: README(s)

- CONTRIBUTING.md
This PR adds contributing.md as per github standards and where people will actually read it.
Please delete https://github.com/frappe/frappe_docker/wiki/Contribution-Guidelines after merge
> Add contributing.md by github standards

- build/frappe-nginx/Dockerfile
- build/frappe-nginx/generate_standard_style_css.js
- build/frappe-nginx/v12.Dockerfile
use nunjucks to render jinja2 template
generate default theme
Indicator not working.
Login, Invalid Login and Success Indicator CSS not working
Indicator also not working in non-docker style (problem with core code)
> fix(frappe-nginx): Generate Standard Style CSS

- build/frappe-nginx/v12.Dockerfile
standard_style.css generation not required for v12
`frappe/website/doctype/website_theme/website_theme_template.scss` doesn't exist in version-12
> revert(frappe-nginx): revert v12.Dockerfile

- build/common/commands/restore_backup.py
ALTER USER fails if user does not exists.
Create/Alter user and grant privileges.
> fix: restore backup grant privileges command

- build/common/nginx-default.conf.template
Trying to fix #231 with setting the Header `origin` to `$http_referer`.
`$http_referer` seems to hold the URL which the request comes from  (e.g. http://erp.example.com) 
Socketio extracts the value from the `origin` header (see here: https://github.com/frappe/frappe/blob/253109e2f9413c5e5851f50ebd54260b0623fbf7/socketio.js#L288)
In my case it fixes the problem but I'm not sure, if it affects something else...
> Fix socketio error in reverse proxy setup

- .devcontainer/docker-compose.yml
When one misses the part of the doc that says bench should be created under /workspace/development, bench is created in home directory and the work would be lost when the container is recreated. Making the directory default would avert that
> Set /workspace/development as default working dir

- docker-compose.yml
- docs/single-bench.md
- env-local
- env-production
In the compose file, removed some quotes for everything to be the same. And in the documentation added HTTP > HTTPS redirection instructions and explained the missing environment variables. Also added a note about the initial site creation time and the default credentials.
> Doc additions and minor fixes

- build/common/nginx-default.conf.template
Implements the fix talked about in #261 and on [frappe/bench/pull/1024](https://github.com/frappe/bench/pull/1024).
> fix: use remote_addr instead of header ip

- build/bench/Dockerfile
Without less installed, tools like bench --site site_name mariadb are not displaying results
> Install less in bench Dockerfile

- build/common/commands/migrate.py
importing migrate() needs frappe.init
> fix: migrate command

- installation/docker-compose-custom.yml
I was unable to `docker-compose up` with custom apps. The reason was that the custom app build files were unreachable from the previous context of `.` which was the path at which `docker-compose-custom.yml` was present. Besides, I thought it better to confine the context to just what the build requires, hence the change in respective contexts.
> fix: custom compose build context

- build/common/nginx-default.conf.template
use $scheme://$http_host instead of $http_referer
fixes socketio
revert https://github.com/frappe/frappe_docker/pull/232
that caused socketio to take host as https://example.com/desk instead of https://example.com
error:
```
100.64.0.39 - - [06/Jul/2020:07:20:07 +0000] "GET /desk/api/method/frappe.realtime.can_subscribe_doc?sid=07da11decda89b875008331f420420420thccbdcbdthccbd16775a&doctype=Selling%20Settings&docname=Selling%20Settings HTTP/1.1" 404 2530 "-" "-" "100.64.1.82"
```
> fix: nginx config

- build/frappe-nginx/docker-entrypoint.sh
Continued from #299.
This sets the `.build` modified time to the newest modified times of all the folders in `/assets`. Every time any of the assets are rebuilt, their modified time updates which in turn does the same to `.build`.
Sorry couldn't update this sooner.
> feat: touch .build

- env-example
- installation/docker-compose-custom.yml
- installation/docker-compose-erpnext.yml
- installation/docker-compose-frappe.yml
When updating our ERPNext deployment, I noticed that you made progress on Kubernetes support. It seems that you introduced more specific version variables for this, namely `FRAPPE_VERSION` and `ERPNEXT_VERSION`.
However, I noticed that the docker-compose files still use the old `VERSION` variable. I replaced them with the correct one so that they work with the new version variables.
> Use new version variables in compose files

- build/common/commands/push_backup.py
- build/common/commands/restore_backup.py
If the backups are stored inside some directory in S3, it is also included in the object list and the line where key is split and assigned to vars break since its a directory object and we only need the desired file inside it.
> fix: do not consider directory objects

- build/common/commands/new.py
mariadb galera helm chart doesn't allow root@% to ALTER mysql.user
> feat(frappe-worker): update user query for mariadb galera

- development/README.md
Since the option --skip-redis-config-generation for bench init do not put redis config into ProcFile this step is not needed for developpement environement
> Update documentation about Honcho's ProcFile (redis is already not included)

- build/common/commands/new.py
Starting with MySQL 8, we no longer can (implicitly) create a user using the `GRANT` command. we should Use `CREATE USER` instead followed by the GRANT statement.
> fix: make new command compatible with MySQL 8

- README.md
- build/common/nginx-default.conf.template
- build/frappe-nginx/docker-entrypoint.sh
- docs/environment-variables.md
nginx timeout can be configured using `HTTP_TIMEOUT` environment variable.
> feat(frappe-nginx): configurable nginx http timeout

- build/bench/Dockerfile
- build/erpnext-nginx/Dockerfile
- build/erpnext-nginx/install_app.sh
- build/erpnext-worker/Dockerfile
- build/frappe-nginx/Dockerfile
- build/frappe-socketio/Dockerfile
- build/frappe-worker/Dockerfile
- Images are made compatible
- No automated builds yet. User will need to build on their own.
- Reason for no automated builds is: pandas takes 2+ hrs to build on arm64. Travis has job running limit for 50 min.
- DOCKER_REGISTRY_PREFIX can be used as build-arg by forks for automated builds.
Github actions has more timeout limit to run jobs. Project can be moved there for automated builds?
Anyway 2+ hrs to build something (2+ x3 for v13,v12,v11) is not sustainable?
> feat: make images arm64 compatible

- build/frappe-worker/Dockerfile
fixes permission denied error during site creation
Error faced in PWD and docker swarm
> fix: sites-vol owned by non-root user

- build/common/nginx-default.conf.template
- build/frappe-nginx/docker-entrypoint.sh
- docs/docker-swarm.md
- docs/environment-variables.md
Currently, frappe-nginx (and subsequently erpnext-nginx) don't report the proper IP/scheme when placed behind a traefik instance.
These changes configure the [nginx real-ip module](http://nginx.org/en/docs/http/ngx_http_realip_module.html) to allow the X-Forwarded-For and X-Forwarded-Proto headers sent by traefik (and other loadbalancers) to be used. 
This enables 3 new environment variables that can be passed:
- UPSTREAM_REAL_IP_ADDRESS  to configure the trusted IP range (to avoid IP spoofing). By default this is 127.0.0.1, but for docker this can be set to 172.17. 0.0/16 (non-swarm) or 10.0.0.0/8 (swarm), or whatever loadbalancer/proxy IP range is being used.
- UPSTREAM_REAL_IP_RECURSIVE to configure the …
> Allow for configuring the realip module for nginx to pass the proper IP/Scheme to frappe

- build/common/worker/docker-entrypoint.sh
- build/frappe-nginx/docker-entrypoint.sh
- build/frappe-socketio/Dockerfile
- build/frappe-socketio/docker-entrypoint.sh
- build/frappe-worker/Dockerfile
- docker-compose.yml
- frappe-installer
- installation/docker-compose-custom.yml
- installation/docker-compose-erpnext.yml
- installation/docker-compose-frappe.yml
This PR introduces rootless containers by default
Running docker containers as root is [extremely unsafe](https://americanexpress.io/do-not-run-dockerized-applications-as-root/) and should be avoided at all times unless no other options are available.
When deploying erpnext to a kubernetes cluster I was forced to run all containers as root with all privileges allowed. I noticed that there has been some thought about this and there is an environment variable called `$RUN_AS_ROOT` that allows to perform some actions as a non-root user. However, the use of this variable is sub-optimal because:
- It's not well …
> Rootless containers by default

- build/common/commands/new.py
`_new_site` has been moved to `installer.py` in frappe/frappe#12447
closes: #431
> fix: change import path for new_site command

- build/common/nginx-default.conf.template
- build/frappe-nginx/docker-entrypoint.sh
- docs/environment-variables.md
The custom NGINX image doesn't allow to set static Host/Site-Name headers. This is required if the app is exposed to an AWS ALB which can't send these headers for doing the healthchecks. Since the healthchecks fail, the target groups are not activated, thus giving 502.
For such environments, the host header has to be hardcoded inside the NGINX config. This change is backwards compatible since it fallbacks to using the original variables inside the config template, only overrides if the user gives them as environment variables in their `docker-compose` configs.
> feat: Add Site name and Host as env variables for NGINX config template

- build/frappe-nginx/docker-entrypoint.sh
- docs/environment-variables.md
Adds `SKIP_NGINX_TEMPLATE_GENERATION` environment variable support to [`frappe-nginx/docker-entrypoint.sh`](https://github.com/frappe/frappe_docker/blob/develop/build/frappe-nginx/docker-entrypoint.sh). The behavior is:
- When set to `1`, will skip the `envsubst` part and the user is expected to mount their own config file.
- Default (`0`), will continue the current behavior of generating the config file from [`nginx-default.conf.template`](https://github.com/frappe/frappe_docker/blob/develop/build/common/nginx-default.conf.template).
Discussed in https://github.com/frappe/frappe_docker/pull/441#issuecomment-808213783. **Marking it as WIP since I'd need to rebase** this once https://github.com/frappe/frappe_docker/pull/441 gets merged.
> Add a flag to skip generating default NGINX config

- docker-compose.yml
suggested in issue https://github.com/frappe/frappe_docker/issues/420
> fix: quick start userns_mode set to host

- docs/docker-swarm.md
Without this variable, erpnext will not be installed when you create a new site job for swarm deployment
> Adding INSTALL_APPS=erpnext env variable to docs

- docs/docker-swarm.md
`frappe-bench-v13_sites_vol` should be `frappe-bench-v13_sites-vol`
> fix: rename volume for creating job

- build/bench/Dockerfile
Looks like it's done in the other Dockerfiles
This should speed up the Docker image build process, make the image smaller.
> Set git clone depth to 1 in build/bench/Dockerfile

- .github/workflows/docker.yml
helm release deploy key uses webfactory/ssh-agent@v0.5.3
test only on PR
docker login only if not PR
> ci: fixes ci steps

- .github/workflows/build_develop.yml
- .github/workflows/build_stable.yml
This fixes the bug when ERPNext images are built upon old Frappe images and test are ran on old images.
Closes #541
> ci: Push images right after build

- build/frappe-socketio/docker-entrypoint.sh
There's no file `frappe/health.js`: neither on version-13 nor on develop.
Also updated `checkConfigExists`, now it is the same as in worker entrypoint
> fix(frappe-socketio): Remove dead `doctor` command

- build/frappe-worker/docker-entrypoint.sh
If FORCE or NO_BACKUP env variables were set to any value it was counted as True. Now works only: FORCE=1 or NO_BACKUP=1
> fix(frappe-worker): Drop flags

- build/erpnext-nginx/Dockerfile
- build/erpnext-worker/Dockerfile
After update in #555 we started installing g++ and gcc in frappe-worker image only on arm64. And it is fine because Frappe doesn't require it on different platforms. Turns out ERPNext does. Since erpnext-worker image inherits from frappe-worker build failed.
Currently on PRs build for Frappe and ERPNext are separate, so this issue is explainable. I will see how we can prevent this in the future.
Closes #557.
> Fix ERPNext build

- .github/workflows/build_stable.yml
one more attempt to fix #562 
name and email used from this discussion https://github.community/t/github-actions-bot-email-address/17204 and https://github.com/fregante/setup-git-user/blob/6cef8bf084d00360a293e0cc3c56e1b45d6502b8/index.js#L5-L6
> ci: use git command to config git creds

- build/frappe-worker/Dockerfile
While building the frappe-worker image, a permissions denied error was being thrown while executing line 80:
`RUN mkdir -p apps logs commands sites /home/frappe/backups`
I now first create the folder as root, change ownership to user frappe before changing to user frappe.
> Fix permission denied error

- .github/workflows/build_develop.yml
- .github/workflows/build_stable.yml
- docker-bake.hcl
- tests/test-erpnext.sh
- tests/test-frappe.sh
Now our workflows have separate jobs for Frappe and ERPNext. It makes impossible to test and prevent bugs relevant to ERPNext images on PRs. This PR fixes it.
Also:
- brought tests for stable builds back. But now they'll run only on PRs,
- added annotations for `docker-bake.hcl`
> Build ERPNext images on top fresh Frappe images

- build/bench/Dockerfile
Currently bench shows warning about editable mode on every call. version 5.7.0 introduces feature that allows to suppress them.
Before:
After:
Reference: https://github.com/frappe/bench/commit/20560c97c4246b2480d7358c722bc9ad13606138
> feat(bench): Skip warnings if envvar BENCH_DEVELOPER set

- docker-compose.yml
- installation/docker-compose-common.yml
- installation/frappe-mariadb.cnf
- tests/pwd.yml
Upgrade mariadb from 10.3 to 10.6, use `command` parameter in docker-compose files instead of copying mysql config file.
This works fine for me in production for a while.
@revant Couple of questions.
1. How do you feel about inline db configuration?
2. Will this break Try in Play With Docker config?
> Upgrade mariadb

- build/bench/Dockerfile
I'm not sure why it worked in previous PR (https://github.com/frappe/frappe_docker/pull/593#issue-1069573878) 🤔 Not it certainly should work.
> fix(bench): Set `BENCH_DEVELOPER` env var in bashrc instead of Dockerfile

- docker-compose.yml
- installation/frappe-postgresql/docker-compose.yml
- tests/pwd.yml
80% of logs come from `traefik` and they are not that useful.
> fix: Remove `--log.level=DEBUG` from traefik command to reduce log verbosity

- docs/site-operations.md
Documentation is making references to an unexisting $VERSION variable. I'm updating it to $ERPNEXT_VERSION.
> Update references to $ERPNEXT_VERSION

- development/README.md
Since frappe_docker now uses the mariadb:10.6 docker image for its database, the `UPDATE mysql.user SET Host = '%' where User = 'db_name'; FLUSH PRIVILEGES;` command fails as _mysql.user_ is deprecated and is now a view to the _mysql.global_priv_ table as from MariaDB 10.4+: [https://mariadb.com/kb/en/mysqluser-table/](url).
> Change mysql.user table to mysql.global_priv table for MariaDB 10.4+

- build/frappe-worker/commands/new.py
After https://github.com/frappe/frappe/pull/16134
`TypeError: _new_site() got an unexpected keyword argument 'mariadb_root_username'`
> fix: new site command on Frappe >13.21.0

- docs/docker-swarm.md
Fix broken Github link in the docker swarm docs pointing to site operation docs.
> Fix broken link in docs.

- docs/images-and-compose-files.md
This change is to inform users to use docker-compose v2. Using v1 can cause problems when parsing the final docker-compose.yaml. Fixes? #701
Expands the documentation to warn users using docker-compose v1.
> Update docs to advise for docker-compose v2

- .github/workflows/build_stable.yml
It failed when Frappe and ERPNext both released new versions. Now it shouldn't fail. To be sure, we need to test it in production.
> Fix example.env workflow failures

- images/worker/Dockerfile
`install-app` script for backend was added in wrong intermediate image.
Fixes #726.
> Add install-app script in final backend image

- requirements-dev.txt
- tests/conftest.py
Prevent tests from modifying $GITHUB_ENV. Also updated Frappe Git URL (git -> https): pip fails to install using git protocol for some reason.
#722
> Fix develop build

- custom_app/README.md
- custom_app/backend.Dockerfile
- custom_app/frontend.Dockerfile
- images/nginx/Dockerfile
- images/nginx/install-app.sh
- images/worker/Dockerfile
- images/worker/install-app.sh
Before, custom app builders could install apps from Git, this prevents it. Issue was that final backend images (frappe and erpnext) didn't have Git installed. In #735 we decided that we should keep Git out of the backend image.
In this PR:
- Remove Git reference from install-app scripts, update Dockerfiles accordingly
- Update custom app guide
- Fix issue with missing sites/assets folder
Fixes #735.
> Remove git reference from install-app

- .github/scripts/update_pwd.py
- .github/workflows/build_stable.yml
- README.md
- pwd.yml
- add pwd button in readme
- add workflow to update pwd.yml
Test:
<a href="https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/revant/frappe_docker/pwd/pwd.yml">
</a>
Wait for 5 minutes for ERPNext site to be created or check `create-site` container logs before opening browser on port 8080. (username: `Administrator`, password: `admin`)
> feat: add PWD button

- .github/workflows/build_develop.yml
- .github/workflows/build_stable.yml
Previously it was not allowed, now it is. Potentially there will be less bugs on changes.
> Use relative path to reusable workflow `docker-build-push`

- development/README.md
- In the app installation step, the provided command was wrong. 
- The command has been fixed.
- I also changed the example command to use version 13 of ERPNext instead of 12, as most will be working on v13.
> Fixed a mistake in app installation command.

- development/README.md
The current container name when not using vs code has a typo. Fixed it.
Thanks for erpnext. It's a great piece of software.
> Fix container name in documentation.

- docs/compose/compose.multi-bench.yaml
With old version, there was not option to run multiple stacks simultaneously
Changed mariadb-network to bench-network in most services. As result, frontend service doesn't see multiple backend services.
> Fix for multiple simultaneous running stacks

- development/README.md
The default NodeJS version is 16 for frappe version 14. Updated that in the `development/README.md`.
> Update default NodeJS version in development/README.md

- .gitignore
- devcontainer-example/docker-compose.yml
- development/README.md
- development/apps-example.json
- development/installer.sh
- Created install scripts for developers.
- Client-centric, where the script can create a new bench/site for the client.
- Configure apps for the client in apps.json, similar to the example file.
- Added relevant documentation.
edit: 
pre-commit lint issues fixed. also marked installer.sh as executable.
shellcheck `SC1091` won't fix.
> feat: install client apps using script

- compose.yaml
- example.env
- images/nginx/Dockerfile
- images/nginx/nginx-template.conf
- pwd.yml
This solves issues with multi document Print, which might take more than 2mins and allows the behaviour to be overridden while keeping the sane defaults
> feat: make proxy read timeout configurable via env

- overrides/compose.multi-bench.yaml
https://discuss.frappe.io/t/service-redis-has-neither-an-image-nor-a-build-context-specified-invalid-compose-project/99936
> fix: redis service context error

- compose.yaml
- pwd.yml
when new apps are added to image, re-running configurator should solve the apps.txt re-generation.
> fix: create apps.txt during configuration

- images/custom/Containerfile
- images/production/Containerfile
reported here https://discuss.frappe.io/t/frappe-docker-2023-production-setup-password-reset-email-link-added-with-port-8000/101844
> fix: default config for production

- overrides/compose.postgres.yaml
because of the missing **/data** in path, there was an issue wherein the data would be lost after docker compose down.
I looked at the official docker hub of postgres and **/var/lib/postgresql/data** this was the default in it as well.
I have attached an image below for reference.
> fix(data persistency): docker volume persistency issue

- example.env
- pwd.yml
The Nginx variable `PROXY_READ_TIMEOUT` is misspelled as `PROXY_READ_TIMOUT`, causing it to not update in the configuration file. This misspelling leads to an issue where the value is not being properly updated in the config file.
This PR will solve the issue and will update variable in configuration file correctly.
> Fix typo in PROXY_READ_TIMEOUT in .env and pwd.yaml

- .github/workflows/build_bench.yml
- docker-bake.hcl
Remove latest tag and make it default
Fixes #1135
Earlier when the bench docker image was build from the develop branch of the[ frappe/bench](https://github.com/frappe/bench) repository, there were issues in the [frappe/bench:latest](https://hub.docker.com/r/frappe/bench) images that caused other applications or sites that used the image to cause error.
And there is only a single bench docker image in the Docker Hub with the tag _latest_. The bench docker image is always replaced by the new bench image, making it difficult to stick to a particular tag of the bench image.
Solution:
Currently whenever a docker image is being build it will check for the latest release of the bench in the [frappe/bench](https://github.com/frappe/bench) repository, and use that as the tag for the new docker …
> Tag bench images with the latest bench release version

- docs/setup-options.md
The setup-options page links to the environment variables, but the link is broken as it has been refactored to a new file in PR #400. This change fixes the broken link to connect to the [environment variables](https://github.com/frappe/frappe_docker/blob/main/docs/environment-variables.md) md file
> Broken link to environment variables definition fixed

- docs/development.md
The Python Version **3.10.12** was deprecated now **3.10.13** is available here the reference link
[PYENV_VERSION](https://hub.docker.com/_/python)
> PYENV_VERSION=3.10.12 deprecated

- .gitignore
- devcontainer-example/devcontainer.json
- pwd.yml
I tend to run open source project locally, preferably by running the docker compose. I ran it using `docker-compose -f ./pwd.yml up -d`.
After running docker compose, the `frontend` container is dead. Doing `docker logs frappe_docker_frontend_1` reveals the log below:
```
2024/01/23 10:46:13 [emerg] 3#3: host not found in upstream "websocket:9000" in /etc/nginx/conf.d/frappe.conf:6
```
This mean the websocket service has not yet started when running frontend. To fix this, I use `depends_on` attribute for the frontend service. https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on.
> frontend depends_on websocket to avoid error on startup

- docs/single-server-example.md
- images/custom/Containerfile
- images/production/Containerfile
Add "gpg" and "less" to the Containerfiles.
fix: #1301 
fix: Add gpg so backup "bench --site yoursite.com backup --with-files --compress" does not fail if encryption is enabled
update: documenation for single server to current status
> fix: Fix gpg and less

- images/bench/Dockerfile
In frappe develop branch (but it will not hurt previous version)
`bench --site XXX restore ....`
will use "file" linux/unix command
https://github.com/frappe/frappe/blob/b044ffedf12989242d29e92fb069518cb306bdfc/frappe/commands/site.py#L176 
It seems that on docker debian:bookworm-slim this command is not installed by default, but it have to be in the bench container
`bench --site XXX restore ....`
This may be required only for development purpose, but still in next frappe release it could be required for production image, depend on how `bench --site XXX restore ....` will be used
> fix: add file cmd install because "bench restore" need it

- README.md
Made grammar corrections, and added links to the prerequisite installations to save someone time if they are not installed.
> fix: grammar and links

- images/custom/Containerfile
- images/production/Containerfile
file package is missing in debian bookworm and it's used in `bench restore` command as mentioned in #1343 
#1343 fixed only the Dockerfile under **bench** this pr fixes the other two under **custom** and **production**
> fix: add missing file package for bench restore

- development/vscode-example/settings.json
See: https://github.com/microsoft/vscode-python/wiki/Setting-descriptions#pythondefaultinterpreterpath
This only adds a default settings.json file to local setup in container to make initial setup a bit more streamlined.
> feat: add defaultInterpreterPath as a vscode setting as a starting point according to docs

- CODE_OF_CONDUCT.md
- compose.yaml
- docs/custom-apps.md
- overrides/compose.https.yaml
- overrides/compose.noproxy.yaml
- overrides/compose.proxy.yaml
- overrides/compose.traefik-ssl.yaml
- overrides/compose.traefik.yaml
This pull request addresses the need highlighted in the issue for enhancing the customization process within Frappe Docker deployments. The current method of manually modifying the `compose.yaml` file for custom applications, as described in the issue, can potentially lead to challenges in version control and file integrity.
To alleviate this, I propose the introduction of environment variables, including `CUSTOM_IMAGE`, `CUSTOM_TAG`, `PULL_POLICY`, `HTTP_PUBLISH_PORT` and `HTTPS_PUBLISH_PORT`, which users can leverage to customize their deployments seamlessly. This approach not only simplifies the customization process but also enhances the maintainability and consistency of Frappe Docker configurations.
By incorporating this feature, users can define their custom image names and tags …
> #1402 Environment variables for custom image

- README.md
As a novice, I played around with Play With Docker and had some success installing manually without Docker, but when it came to running Docker Compose locally on my own machine I got very lost. 
My proposal here is to add an additional step to help people in a similar position to make sure they can easily follow the quick start guide.
> fix: make docs more explicit for beginners

- images/bench/Dockerfile
- images/custom/Containerfile
- images/production/Containerfile
This changes the casing of the `FROM` instruction to be consistent.
It fixes the following warning which seems to have appeared with the release of Docker 27:
>  => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 133)
> Fix: WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match

- images/bench/Dockerfile
- images/custom/Containerfile
- images/production/Containerfile
Fix: LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format
This seems to be a [warning brought in by recent Docker updates.](https://docs.docker.com/reference/build-checks/legacy-key-value-format/)
> Fix: LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format

- docs/setup_for_linux_mac.md
- overrides/compose.mariadb-shared.yaml
- overrides/compose.mariadb.yaml
- pwd.yml
Increase health-check margin in case of any minor delays on MariaDB boot. The current time limit is quite short.
fixes #1484
> Increase mariadb health-check timeout - fixes #1484

- README.md
- images/production/Containerfile
Prompt will show following message.
```shell
Commands restricted in prodution container, Read FAQ before you proceed: https://frappe.fyi/ctr-faq
frappe:~/frappe-bench$
```
> chore: add link to FAQ in production container

- docker-bake.hcl
- images/layered/Containerfile
- images/production/Containerfile
speed up build time
pull builder image
pack built assets into base image
> feat: allow layered custom image build

- compose.yaml
Nested interpolation is not supported by docker (https://github.com/docker/cli/issues/4265). Changed the file so that it uses `CUSTOM_TAG` or `ERPNEXT_VERSION` if that's not available.
Fixes an issue where the compose file incorrectly throws an error below: (already reported in #1487)
```
invalid interpolation format for services.scheduler.image: "${ERPNEXT_VERSION:?No ERPNext version or tag set". You may need to escape any $ with another $.
```
> fix: invalid nested interpolation (#1487)

- .github/workflows/docker-build-push.yml
To include arm64 build in https://hub.docker.com/r/frappe/erpnext/tags
To support arm64 container image
> Update docker-build-push.yml to support arm64

- .github/workflows/docker-build-push.yml
- docker-bake.hcl
Following images now available
- `frappe/base:develop`
- `frappe/build:develop`
- `frappe/erpnext:develop`
> ci: push frappe or erpnext branch as tag

- development/installer.py
--no-mariadb-socket is DEPRECATED; use --mariadb-user-host-login-scope='%' (wildcard) or --mariadb-user-host-login-scope=<myhostscope>, instead.
> fix: --no-mariadb-socket is DEPRECATED

- docs/troubleshoot.md
Add create command template on troubleshoot.md
Add create user command for mariadb in troubleshoot.md
There is some edge cases, like mine running nexterp on synology nas where for some reason the maria db user for nexterp is not created it in the db container, but can be hot fixed created the corresponding user in the db, the current documentation only explain how to update the user, assuming was created it, but adding the non-exiting user fix can help other no typical user
> Update troubleshoot.md for edge cases

- resources/nginx-template.conf
This was not EASY. Don't judge by the diff. This fix comes after hours and hours of calls with @revant 😅
> fix: pwd SocketIO Origin in nginx conf

- docs/setup_for_linux_mac.md
- overrides/compose.redis.yaml
- overrides/compose.traefik-ssl.yaml
- pwd.yml
This pull request addresses an issue where the assets.json file, now stored in Redis by Frappe, persists across new image builds due to the Redis cache volume being persistent. This prevents updates to assets.json from being reflected after a new build.
The proposed change removes the persistent volume for redis-cache, ensuring that the cache, including assets.json, is cleared during each new image deployment.
By removing the persistent Redis volume, we prevent outdated assets.json data from being retained, ensuring the application always works with the latest assets after a build. This eliminates the need for manual intervention or additional automation to clear the cache.
Retaining the old assets.json file will cause the websites to miss certain assets:
Without this change, developers …
> Remove redis-cache volume

- compose.yaml
- overrides/compose.https.yaml
- overrides/compose.mariadb.yaml
- overrides/compose.redis.yaml
Addes restart policy to compose.yaml
Futhermore added restart policy to overriders:
- overrides/compose.mariadb.yaml
- overrides/compose.redis.yaml
- overrides/compose.https.yaml
Resolves #1562
> Compose with restart

- docs/development.md
Clarify documentation about error.
I was following along the development doc to start creating a new custom app.
I faced this error with no apparent solution:
Searching for the message error I found this at discuss: https://discuss.frappe.io/t/youre-attempting-to-install-erpnext-version-15-with-frappe-version-16-this-is-not-supported-and-wi/127422
> doc: Clarify development.md

- development/vscode-example/launch.json
- development/vscode-example/tasks.json
When running the debug on vscode, if I stop it through the UI, the honcho process won't properly receive the SIGINT (Ctrl+C) to be finished.
The second time you try to run it, the port `9000` will still be in use because of the not finished processes and you'd have to restart the container. That was really annoying.
<details><summary>Details</summary>
<p>
```shell
18:49:57 system           | socketio.1 started (pid=370139)
18:49:58 socketio.1       | node:events:495
18:49:58 socketio.1       |       throw er; // Unhandled 'error' event
18:49:58 socketio.1       |       ^
18:49:58 socketio.1       | 
18:49:58 …
```
> chore: Update vscode-example scripts

- docs/single-server-example.md
Since the password would be parsed in single quote (') the text transformation is no longer needed. This update is based on issue #1002 (Unable to login to Traefik Dashboard even after providing Correct password in Basic Auth.)
> Update Install Traefik Section

- docs/site-operations.md
Update to use new docker syntax now that `docker compose` has been standard for more than a few years.
> Use `docker compose` instead of `docker-compose`

- docs/site-operations.md
Reverts frappe/frappe_docker#1702 since the `-p` command is not available on the base `docker` command and is only available on the `docker compose` command.
Sorry for the confusion!
> Revert "Use `docker compose` instead of `docker-compose`"
